spring.application.name=spring-security



# = DATA SOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# = JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# = POSTGRES DIALECT
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# = SERVER
server.port=8080

# = JWT CONFIG
app.jwt.secret=your-256-bit-secret-key-for-jwt-signature-change-this-in-production-with-a-strong-key
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Spring Security Configuration
spring.security.filter.order=10


# == Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abuhuzaifaw5@gmail.com
spring.mail.password=tuyndkzhlykysbsf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
